version: '3.4'


networks:
  dev:
    driver: bridge



volumes:
  app_data:


services:
  backend:
    container_name: backend
    image: ${DOCKER_REGISTRY-}comfywebapi
    ports:
      - "20080:80"
      - "20443:443"
    build:
      context: .
      dockerfile: Comfy.WebApi/Dockerfile
    depends_on:
      - db
    networks:
      - dev
     

  db:
    container_name: database
    image: mariadb:10.9.5
    restart: always
    volumes:
      - app_data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=comfy
    ports:
      - "23306:3306"
    networks:
      - dev


    